/**
 * Sky — astronomically placed Sun and Moon discs plus stars (docs/world.md §Sky).
 * Pure position math (sunPosition / moonPosition, NOOA low-precision, ±2°) plus
 * the thin THREE wrappers (makeSky / updateSky). No relighting — the discs are
 * just visible geometry against the black sky.
 */
import * as THREE from 'three';
import { mulberry32 } from '../data/synthetic';

/** Degrees → radians. */
const DEG = Math.PI / 180;

/** Radians → degrees. */
const RAD = 180 / Math.PI;

/** Distance of the sun/moon discs from the sky group / camera (metres). */
const BODY_RADIUS = 1200;

/** Distance of the star points from the sky group / camera (metres). */
const STAR_RADIUS = 1300;

/** Reused by `direction` / `updateSky` so celestial updates do not allocate. */
const _dir = new THREE.Vector3();
const _lookAtTarget = new THREE.Vector3();

/** Number of stars generated by `makeSky`. */
const STAR_COUNT = 300;

/** Rounds a value into [0, mod). */
function modPos(a: number, mod: number): number {
  return ((a % mod) + mod) % mod;
}

/** The three visible children makeSky creates, so updateSky can move/toggle them. */
interface SkyChildren {
  sun: THREE.Mesh;
  moon: THREE.Mesh;
  stars: THREE.Points;
}

/**
 * A unit direction vector for a celestial body given its azimuth (degrees,
 * clockwise from north) and altitude (degrees), using the locked x/z/y mapping
 * from docs/architecture.md §3.
 */
function direction(azimuthDeg: number, altitudeDeg: number): THREE.Vector3 {
  // dir = (sin A·cos h, sin h, −cos A·cos h)
  const a = azimuthDeg * DEG;
  const h = altitudeDeg * DEG;
  return _dir.set(
    Math.sin(a) * Math.cos(h),
    Math.sin(h),
    -Math.cos(a) * Math.cos(h),
  );
}

/**
 * Convert a right ascension / declination (degrees) plus the day number into a
 * local altitude / azimuth (degrees) for the given latitude/longitude.
 */
function altAzFromRaDec(
  raDeg: number,
  decDeg: number,
  n: number,
  latDeg: number,
  lonDeg: number,
): { azimuthDeg: number; altitudeDeg: number } {
  const gms = modPos(18.697374558 + 24.06570982441908 * n, 24);
  let Hdeg = gms * 15 + lonDeg - raDeg;
  Hdeg = modPos(Hdeg + 180, 360) - 180; // hour angle in (−180, 180]
  const H = Hdeg * DEG;
  const phi = latDeg * DEG;
  const alt = Math.asin(
    Math.sin(phi) * Math.sin(decDeg * DEG) +
      Math.cos(phi) * Math.cos(decDeg * DEG) * Math.cos(H),
  );
  const az = modPos(Math.atan2(Math.sin(H), Math.cos(H) * Math.sin(phi) - Math.tan(decDeg * DEG) * Math.cos(phi)) * RAD + 180, 360);
  return { azimuthDeg: az, altitudeDeg: alt * RAD };
}

/**
 * NOAA low-precision sun position for a date/location (docs/world.md §Sky).
 * Accuracy ≈ ±2°; azimuth 0–360° clockwise from north, altitude degrees.
 */
export function sunPosition(
  date: Date,
  latDeg: number,
  lonDeg: number,
): { azimuthDeg: number; altitudeDeg: number } {
  const jd = date.getTime() / 86400000 + 2440587.5;
  const n = jd - 2451545.0;
  const Ldeg = modPos(280.46 + 0.9856474 * n, 360);
  const gdeg = modPos(357.528 + 0.9856003 * n, 360);
  const g = gdeg * DEG;
  const lambdaDeg = Ldeg + 1.915 * Math.sin(g) + 0.02 * Math.sin(2 * g);
  const epsDeg = 23.439 - 4e-7 * n;
  const lambda = lambdaDeg * DEG;
  const eps = epsDeg * DEG;
  const delta = Math.asin(Math.sin(eps) * Math.sin(lambda));
  const alpha = Math.atan2(Math.cos(eps) * Math.sin(lambda), Math.cos(lambda));
  return altAzFromRaDec(alpha * RAD, delta * RAD, n, latDeg, lonDeg);
}

/**
 * Low-precision lunar position and illuminated fraction for a date/location
 * (docs/world.md §Sky); fraction in [0, 1]. Accuracy ≈ ±2°.
 */
export function moonPosition(
  date: Date,
  latDeg: number,
  lonDeg: number,
): { azimuthDeg: number; altitudeDeg: number; fraction: number } {
  const jd = date.getTime() / 86400000 + 2440587.5;
  const n = jd - 2451545.0;
  const Lm = 218.316 + 13.176396 * n;
  const Mm = 134.963 + 13.064993 * n;
  const F = 93.272 + 13.22935 * n;
  const lambdaMdeg = Lm + 6.289 * Math.sin(Mm * DEG);
  const betaMdeg = 5.128 * Math.sin(F * DEG);
  const epsDeg = 23.439 - 4e-7 * n;
  const eps = epsDeg * DEG;
  const lm = lambdaMdeg * DEG;
  const bm = betaMdeg * DEG;
  const delta = Math.asin(
    Math.sin(bm) * Math.cos(eps) + Math.cos(bm) * Math.sin(eps) * Math.sin(lm),
  );
  const alpha = Math.atan2(
    Math.sin(lm) * Math.cos(eps) - Math.tan(bm) * Math.sin(eps),
    Math.cos(lm),
  );
  const { azimuthDeg, altitudeDeg } = altAzFromRaDec(alpha * RAD, delta * RAD, n, latDeg, lonDeg);

  // Sun's ecliptic longitude for the illumination fraction (same degree base).
  const Lsun = modPos(280.46 + 0.9856474 * n, 360);
  const gsun = modPos(357.528 + 0.9856003 * n, 360);
  const lambdaSunDeg = Lsun + 1.915 * Math.sin(gsun * DEG) + 0.02 * Math.sin(2 * gsun * DEG);
  const fraction = (1 - Math.cos((lambdaMdeg - lambdaSunDeg) * DEG)) / 2;
  return { azimuthDeg, altitudeDeg, fraction };
}

/**
 * Build the sky group for a date/origin: sun and moon discs plus seeded stars,
 * positioned and toggled via `updateSky` (docs/world.md §Sky).
 */
export function makeSky(
  date: Date,
  origin: { lat: number; lon: number },
  seed = 5,
): THREE.Group {
  const group = new THREE.Group();

  const sun = new THREE.Mesh(
    new THREE.CircleGeometry(45, 24),
    new THREE.MeshBasicMaterial({ color: 0xfff2b0, fog: false }),
  );
  const moon = new THREE.Mesh(
    new THREE.CircleGeometry(32, 24),
    new THREE.MeshBasicMaterial({ color: 0xd9dbe4, transparent: true, opacity: 0.5, fog: false }),
  );
  group.add(sun, moon);

  // Stars: 300 mulberry32-seeded directions with altitude 5°–85°, radius 1300.
  const rand = mulberry32(seed);
  const positions = new Float32Array(STAR_COUNT * 3);
  for (let i = 0; i < STAR_COUNT; i++) {
    const alt = 5 + rand() * 80;
    const az = rand() * 360;
    const dir = direction(az, alt).multiplyScalar(STAR_RADIUS);
    positions[i * 3] = dir.x;
    positions[i * 3 + 1] = dir.y;
    positions[i * 3 + 2] = dir.z;
  }
  const starGeo = new THREE.BufferGeometry();
  starGeo.setAttribute('position', new THREE.BufferAttribute(positions, 3));
  const stars = new THREE.Points(
    starGeo,
    new THREE.PointsMaterial({
      size: 3,
      color: 0x9fb4c8,
      fog: false,
      sizeAttenuation: false,
    }),
  );
  group.add(stars);

  group.userData = { sun, moon, stars } satisfies SkyChildren;
  updateSky(group, date, origin);
  return group;
}

/**
 * Move/toggle the sky's existing sun/moon/stars for a new date — no allocation.
 * Sun (and moon) visible when above the horizon (alt > −2°); stars only when
 * the sun is well below it (alt < −6°). Discs face the group centre (the
 * camera), not the world origin.
 */
export function updateSky(
  group: THREE.Group,
  date: Date,
  origin: { lat: number; lon: number },
): void {
  const { sun, moon, stars } = group.userData as SkyChildren;
  const sunPos = sunPosition(date, origin.lat, origin.lon);
  const moonPos = moonPosition(date, origin.lat, origin.lon);

  group.getWorldPosition(_lookAtTarget);

  const sunDir = direction(sunPos.azimuthDeg, sunPos.altitudeDeg).multiplyScalar(BODY_RADIUS);
  sun.position.set(sunDir.x, sunDir.y, sunDir.z);
  sun.lookAt(_lookAtTarget);
  sun.visible = sunPos.altitudeDeg > -2;

  const moonDir = direction(moonPos.azimuthDeg, moonPos.altitudeDeg).multiplyScalar(BODY_RADIUS);
  moon.position.set(moonDir.x, moonDir.y, moonDir.z);
  moon.lookAt(_lookAtTarget);
  (moon.material as THREE.MeshBasicMaterial).opacity =
    0.25 + 0.75 * moonPos.fraction;
  moon.visible = moonPos.altitudeDeg > -2;

  stars.visible = sunPos.altitudeDeg < -6;
}
